#!/bin/sh /etc/rc.common

USE_PROCD=1
START=91

URL=https://cloud.internalpositioning.com
FAMILY=
CSV=/tmp/airodumpscan.csv

start_service() {
    [ -f $CSV ] || (echo "No airodump csv file found. Start airodump service first" && return 1)

  procd_open_instance airodumpscan
  procd_set_param command python3 /root/airodumpscan.py -i $CSV -u $URL
  procd_set_param respawn ${respawn_threshold:-3600}
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_close_instance
}
