#!/bin/sh /etc/rc.common

USE_PROCD=1
START=91

URL=https://cloud.internalpositioning.com
FAMILY=
FIFO=/tmp/logfile

start_service() {
  [ ! -f $FIFO ] || echo "No system log file found. Configure logd output in /etc/config/system first" && return 1

  procd_open_instance tcpdumpscan
  procd_set_param command python3 /root/tcpdumpscan.py -i $FIFO -u $URL
  procd_set_param respawn ${respawn_threshold:-3600}
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_close_instance
}
