#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99

URL=https://cloud.internalpositioning.com
FAMILY=

find_monitor() {
  local phys=$(ls /sys/class/ieee80211/)
  for phy in $phys; do
    local type=$(cat /sys/class/ieee80211/$phy/device/net/*/type)
    if [ $type -ne 1 -a $type -ne 0 ]; then
      IFACE=$(ls /sys/class/ieee80211/$phy/device/net)
    fi
  done
}    

start_service() {
  find_monitor 
  [ ! -z "$IFACE" ] || (echo "No interfaces found in monitor mode. Bailing out." && exit 1)

  procd_open_instance tcpdumpscan
  procd_set_param command python3 /root/tcpdumpscan.py -i $IFACE -u $URL -f $FAMILY
  procd_set_param respawn ${respawn_threshold:-3600}
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_close_instance
}

service_triggers()
{
    procd_add_reload_trigger "network" "wireless"
}
