#!/bin/sh /etc/rc.common

USE_PROCD=1
START=90

find_monitor() {
  local phys=$(ls /sys/class/ieee80211/)
  for phy in $phys; do
    local type=$(cat /sys/class/ieee80211/$phy/device/net/*/type)
    if [ $type -ne 1 -a $type -ne 0 ]; then
      IFACE=$(ls /sys/class/ieee80211/$phy/device/net)
    fi
  done
}    

start_service() {
  find_monitor 
  [ ! -z $IFACE ] || (echo "No interfaces found in monitor mode. Bailing out." && return 1)
  
  procd_open_instance tcpdump
  procd_set_param command tcpdump -l -i $IFACE -e -s 256 type mgt subtype probe-req
  procd_set_param stdout 1 # forward to logread
  procd_set_param stderr 1 # same for stderr
  procd_close_instance
}
